site:
  name: Soberania Digital
  site: 'https://soberania.digital'
  base: '/'
  trailingSlash: false

metadata:
  title:
    default: Soberania Digital
    template: '%s — Soberania Digital'
  description: 'Rede para debates, trocas de informações e organização de ações pela Soberania Digital. Sua participação é fundamental para construirmos um futuro digital!'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Soberania.digital
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@soberania'
    site: '@soberania'
    cardType: summary_large_image

i18n:
  language: pt-BR
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'dark:only'
